---
- name: Install Pikodi utils on Osmc distribution
  hosts: all
  become: true

  environment:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

  tasks:

    - include: /src/kodi/get_version.yml
    - include: /src/kodi/alpha_18.yml
      when: kodi_version is version('18', '<')

    - name: "Install docker"
      apt:
        name: docker

    - name: Install dependecies (1/3)
      apt:
        name: "{{requested_apt_packages}}"
    - name: Install dependecies (2/3)
      pip:
        name: setuptools
        state: latest
    - name: Install dependecies (3/3)
      pip:
        name: "{{requested_pip_packages}}"
        state: latest

    - include: /src/xboxcontroller/play.yml

    - include: /src/linkdd/play.yml

    - include: /src/retropie/play.yml

    - name: "Install Addons"
      include: /src/kodi/addon.yml
      loop: "{{addons}}"
      loop_control:
        loop_var: addon

    - include: /src/kodi/reboot.yml
