#!/bin/sh
# /etc/init.d/xboxdrv
### BEGIN INIT INFO
# Provides:          my-service-name
# Required-Start:    $all
# Required-Stop:
# Default-Start:     2 3 4 5
# Default-Stop:
# Short-Description: your description here
### END INIT INFO

case "$1" in
start)
    sudo rmmod xpad
    sudo modprobe uinput
    sudo modprobe joydev
    sudo /usr/bin/xboxdrv --config /home/osmc/xbmc.ini --detach-kernel-driver --id 0 --led 0 --silent & sleep 1
    sudo /usr/bin/xboxdrv --config /home/osmc/xbmc.ini --detach-kernel-driver --id 1 --led 3 --silent & sleep 1
    exit 0
    ;;
stop)
    killall xboxdrv
    ;;
*)
    echo "Usage: /etc/init.d/xboxdrv {start|stop}"
    exit 1
    ;;
esac

exit 0
