proxy:
  image: jwilder/nginx-proxy
  ports:
    - "80:80"
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock

portainer:
  image: portainer/portainer
#   restart: always
  hostname: 'portainer.local'
  volumes:
    - '/var/run/docker.sock:/var/run/docker.sock'
  expose:
    - 9000
  ports:
    - 8081:9000
  environment:
    - "VIRTUAL_HOST=portainer.local"
    - "VIRTUAL_PORT=8081"

gitlab:
  image: 'gitlab/gitlab-ce:latest'
  hostname: 'gitlab.local'
  environment:
    # - VIRTUAL_HOST=gitlab.local
    - "GITLAB_OMNIBUS_CONFIG=external_url 'http://gitlab.local:8082'"
    - "VIRTUAL_HOST=gitlab.local"
    - "VIRTUAL_PORT=8082"
  expose:
    - 8082
  ports:
    - '8082:80'
  volumes:
    - '/srv/gitlab/config:/etc/gitlab'
    - '/srv/gitlab/logs:/var/log/gitlab'
    - '/srv/gitlab/data:/var/opt/gitlab'
