#!/bin/bash


# if option juste relaunch playlist
if [ $# == 0 ]
then

###########################
#
# Random email
#
###########################

i=$(date +%s | tail -c 2)
i=$(($i+3))
email=$(date | md5sum | tr '0123456789' 'guelfoitpm')
email=${email:1:$i}
password=$(date | md5sum)
password=${password:1:10}

echo $email
echo $password

###########################
#
# Create Account
#
###########################

wget https://www.nakednews.com/account/signup?source=join-modal -O /tmp/bip &> /dev/null

token=$(cat /tmp/bip | tr -d '\n')
token=${token#*name=\"authenticity_token\" type=\"hidden\" value=\"}
token=${token:0:100}
token=${token%\" /></div>*}

echo "token : $token"

curl -F "utf8=✓" -F "authenticity_token=${token}" -F "source=join-modal" -F "token=" -F "return_url=" -F "email=${email}@yopmail.fr" -F "password=${password}" -F "optin=0" https://www.nakednews.com/account/signup &> /dev/null

###########################
#
# Activate account
#
###########################

sleep 60

wget "http://yopmail.fr/inbox.php?login=${email}&p=r&d=&ctrl=&scrl=&spam=true&v=2.6&r_c=&id=" -O /tmp/bla &> /dev/null

str=$(cat /tmp/bla)
str=${str#*class=\"lm\" href=\"}
str=${str:0:200}
str=${str%\"><span class=\"lmfd*}

wget "http://yopmail.fr/${str}" -O /tmp/blurp &> /dev/null

str=$(cat /tmp/blurp)
str=${str#*style=\"font-size:26px;font-weight:bold;text-decoration:none;\" href=\"}
str=$(echo ${str:0:500} | tr -d '\n')
str=${str%rel=\"nofollow*}


###########################
#
# Create playlist
#
###########################

echo "url : $str"

wget "$str" -O /tmp/bouh &> /dev/null

echo "Streams :"

amp="&amp;"
quote="&quot;"
_quote="'"
_amp="&"

streams=$(cat /tmp/bouh)
streams=${streams#*id=\"program-player-container_video\" data-video=\'\{}
streams=${streams%\}\' data-setup=\'\{&quot;preview&quot;:true\}\'*}
streams=${streams//$quote/$_quote}
streams=${streams//$amp/$_amp}
streams=$(echo $streams | tr "," "\n")
streams=$(echo $streams | tr "'" "\n")

echo '#EXTM3U' > /tmp/nnpl.m3u
count=0

for stream in $streams
do
    if [[ $stream == *".mp4"* ]]
    then
        echo "#EXTINF:$count,NN$count" >> /tmp/nnpl.m3u
        echo "$stream" >> /tmp/nnpl.m3u
        #ssh osmc@192.168.1.10 "xbmc-send --action='PlayMedia($stream)'"
        count=$((count + 1))
    fi
done

cat /tmp/nnpl.m3u

fi

scp /tmp/nnpl.m3u osmc@192.168.1.10:/tmp/
ssh osmc@192.168.1.10 "xbmc-send --action='PlayMedia(/tmp/nnpl.m3u)'"

#/cygdrive/c/Users/Pierre/AppData/Local/Vivaldi/Application/vivaldi.exe --incognito $str

# rm -f /tmp/bip
# rm -f /tmp/bla
# rm -f /tmp/blurp
# rm -f /tmp/bouh
# rm -f /tmp/nnpl.m3u

exit
