#! /bin/sh
# /etc/init.d/vhusb
#

# Carry out specific functions when asked to by the system
case "$1" in
start)
    sudo vhusb
    ;;
stop)
    sudo killall vhusb
    ;;
*)
    echo "Usage: /etc/init.d/vhusb {start|stop}"
    exit 1
    ;;
esac

exit 0
